package com.example.tweak.danabusbooking.database_management.controllers.tram_dung;

public class TramDungData {

    public static final int[] MA_TRAM_DUNG = {
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120
    };

    public static final String[] TEN_TRAM_DUNG = {
            "Trạm dừng An Toàn 1",
            "Trạm dừng An Toàn 2",
            "Trạm dừng An Toàn 3",
            "Trạm dừng An Toàn 4",
            "Trạm dừng An Toàn 5",
            "Trạm dừng An Toàn 6",
            "Trạm dừng An Toàn 7",
            "Trạm dừng An Toàn 8",
            "Trạm dừng An Toàn 9",
            "Trạm dừng An Toàn 10",
            "Trạm dừng An Toàn 11",
            "Trạm dừng An Toàn 12",
            "Trạm dừng An Toàn 13",
            "Trạm dừng An Toàn 14",
            "Trạm dừng An Toàn 15",
            "Trạm dừng An Toàn 16",
            "Trạm dừng An Toàn 17",
            "Trạm dừng An Toàn 18",
            "Trạm dừng An Toàn 19",
            "Trạm dừng An Toàn 20",
            "Trạm dừng An Toàn 21",
            "Trạm dừng An Toàn 22",
            "Trạm dừng An Toàn 23",
            "Trạm dừng An Toàn 24",
            "Trạm dừng An Toàn 25",
            "Trạm dừng An Toàn 26",
            "Trạm dừng An Toàn 27",
            "Trạm dừng An Toàn 28",
            "Trạm dừng An Toàn 29",
            "Trạm dừng An Toàn 30",
            "Trạm dừng An Toàn 31",
            "Trạm dừng An Toàn 32",
            "Trạm dừng An Toàn 33",
            "Trạm dừng An Toàn 34",
            "Trạm dừng An Toàn 35",
            "Trạm dừng An Toàn 36",
            "Trạm dừng An Toàn 37",
            "Trạm dừng An Toàn 38",
            "Trạm dừng An Toàn 39",
            "Trạm dừng An Toàn 40",
            "Trạm dừng An Toàn 41",
            "Trạm dừng An Toàn 42",
            "Trạm dừng An Toàn 43",
            "Trạm dừng An Toàn 44",
            "Trạm dừng An Toàn 45",
            "Trạm dừng An Toàn 46",
            "Trạm dừng An Toàn 47",
            "Trạm dừng An Toàn 48",
            "Trạm dừng An Toàn 49",
            "Trạm dừng An Toàn 50",
            "Trạm dừng An Toàn 51",
            "Trạm dừng An Toàn 52",
            "Trạm dừng An Toàn 53",
            "Trạm dừng An Toàn 54",
            "Trạm dừng An Toàn 55",
            "Trạm dừng An Toàn 56",
            "Trạm dừng An Toàn 57",
            "Trạm dừng An Toàn 58",
            "Trạm dừng An Toàn 59",
            "Trạm dừng An Toàn 60",
            "Trạm dừng An Toàn 61",
            "Trạm dừng An Toàn 62",
            "Trạm dừng An Toàn 63",
            "Trạm dừng An Toàn 64",
            "Trạm dừng An Toàn 65",
            "Trạm dừng An Toàn 66",
            "Trạm dừng An Toàn 67",
            "Trạm dừng An Toàn 68",
            "Trạm dừng An Toàn 69",
            "Trạm dừng An Toàn 70",
            "Trạm dừng An Toàn 71",
            "Trạm dừng An Toàn 72",
            "Trạm dừng An Toàn 73",
            "Trạm dừng An Toàn 74",
            "Trạm dừng An Toàn 75",
            "Trạm dừng An Toàn 76",
            "Trạm dừng An Toàn 77",
            "Trạm dừng An Toàn 78",
            "Trạm dừng An Toàn 79",
            "Trạm dừng An Toàn 80",
            "Trạm dừng An Toàn 81",
            "Trạm dừng An Toàn 82",
            "Trạm dừng An Toàn 83",
            "Trạm dừng An Toàn 84",
            "Trạm dừng An Toàn 85",
            "Trạm dừng An Toàn 86",
            "Trạm dừng An Toàn 87",
            "Trạm dừng An Toàn 88",
            "Trạm dừng An Toàn 89",
            "Trạm dừng An Toàn 90",
            "Trạm dừng An Toàn 91",
            "Trạm dừng An Toàn 92",
            "Trạm dừng An Toàn 93",
            "Trạm dừng An Toàn 94",
            "Trạm dừng An Toàn 95",
            "Trạm dừng An Toàn 96",
            "Trạm dừng An Toàn 97",
            "Trạm dừng An Toàn 98",
            "Trạm dừng An Toàn 99",
            "Trạm dừng An Toàn 100",
            "Trạm dừng An Toàn 101",
            "Trạm dừng An Toàn 102",
            "Trạm dừng An Toàn 103",
            "Trạm dừng An Toàn 104",
            "Trạm dừng An Toàn 105",
            "Trạm dừng An Toàn 106",
            "Trạm dừng An Toàn 107",
            "Trạm dừng An Toàn 108",
            "Trạm dừng An Toàn 109",
            "Trạm dừng An Toàn 110",
            "Trạm dừng An Toàn 111",
            "Trạm dừng An Toàn 112",
            "Trạm dừng An Toàn 113",
            "Trạm dừng An Toàn 114",
            "Trạm dừng An Toàn 115",
            "Trạm dừng An Toàn 116",
            "Trạm dừng An Toàn 117",
            "Trạm dừng An Toàn 118",
            "Trạm dừng An Toàn 119",
            "Trạm dừng An Toàn 120"
    };

    public static final String[] DIA_CHI = {
            "Địa chi An Toàn 1",
            "Địa chi An Toàn 2",
            "Địa chi An Toàn 3",
            "Địa chi An Toàn 4",
            "Địa chi An Toàn 5",
            "Địa chi An Toàn 6",
            "Địa chi An Toàn 7",
            "Địa chi An Toàn 8",
            "Địa chi An Toàn 9",
            "Địa chi An Toàn 10",
            "Địa chi An Toàn 11",
            "Địa chi An Toàn 12",
            "Địa chi An Toàn 13",
            "Địa chi An Toàn 14",
            "Địa chi An Toàn 15",
            "Địa chi An Toàn 16",
            "Địa chi An Toàn 17",
            "Địa chi An Toàn 18",
            "Địa chi An Toàn 19",
            "Địa chi An Toàn 20",
            "Địa chi An Toàn 21",
            "Địa chi An Toàn 22",
            "Địa chi An Toàn 23",
            "Địa chi An Toàn 24",
            "Địa chi An Toàn 25",
            "Địa chi An Toàn 26",
            "Địa chi An Toàn 27",
            "Địa chi An Toàn 28",
            "Địa chi An Toàn 29",
            "Địa chi An Toàn 30",
            "Địa chi An Toàn 31",
            "Địa chi An Toàn 32",
            "Địa chi An Toàn 33",
            "Địa chi An Toàn 34",
            "Địa chi An Toàn 35",
            "Địa chi An Toàn 36",
            "Địa chi An Toàn 37",
            "Địa chi An Toàn 38",
            "Địa chi An Toàn 39",
            "Địa chi An Toàn 40",
            "Địa chi An Toàn 41",
            "Địa chi An Toàn 42",
            "Địa chi An Toàn 43",
            "Địa chi An Toàn 44",
            "Địa chi An Toàn 45",
            "Địa chi An Toàn 46",
            "Địa chi An Toàn 47",
            "Địa chi An Toàn 48",
            "Địa chi An Toàn 49",
            "Địa chi An Toàn 50",
            "Địa chi An Toàn 51",
            "Địa chi An Toàn 52",
            "Địa chi An Toàn 53",
            "Địa chi An Toàn 54",
            "Địa chi An Toàn 55",
            "Địa chi An Toàn 56",
            "Địa chi An Toàn 57",
            "Địa chi An Toàn 58",
            "Địa chi An Toàn 59",
            "Địa chi An Toàn 60",
            "Địa chi An Toàn 61",
            "Địa chi An Toàn 62",
            "Địa chi An Toàn 63",
            "Địa chi An Toàn 64",
            "Địa chi An Toàn 65",
            "Địa chi An Toàn 66",
            "Địa chi An Toàn 67",
            "Địa chi An Toàn 68",
            "Địa chi An Toàn 69",
            "Địa chi An Toàn 70",
            "Địa chi An Toàn 71",
            "Địa chi An Toàn 72",
            "Địa chi An Toàn 73",
            "Địa chi An Toàn 74",
            "Địa chi An Toàn 75",
            "Địa chi An Toàn 76",
            "Địa chi An Toàn 77",
            "Địa chi An Toàn 78",
            "Địa chi An Toàn 79",
            "Địa chi An Toàn 80",
            "Địa chi An Toàn 81",
            "Địa chi An Toàn 82",
            "Địa chi An Toàn 83",
            "Địa chi An Toàn 84",
            "Địa chi An Toàn 85",
            "Địa chi An Toàn 86",
            "Địa chi An Toàn 87",
            "Địa chi An Toàn 88",
            "Địa chi An Toàn 89",
            "Địa chi An Toàn 90",
            "Địa chi An Toàn 91",
            "Địa chi An Toàn 92",
            "Địa chi An Toàn 93",
            "Địa chi An Toàn 94",
            "Địa chi An Toàn 95",
            "Địa chi An Toàn 96",
            "Địa chi An Toàn 97",
            "Địa chi An Toàn 98",
            "Địa chi An Toàn 99",
            "Địa chi An Toàn 100",
            "Địa chi An Toàn 101",
            "Địa chi An Toàn 102",
            "Địa chi An Toàn 103",
            "Địa chi An Toàn 104",
            "Địa chi An Toàn 105",
            "Địa chi An Toàn 106",
            "Địa chi An Toàn 107",
            "Địa chi An Toàn 108",
            "Địa chi An Toàn 109",
            "Địa chi An Toàn 110",
            "Địa chi An Toàn 111",
            "Địa chi An Toàn 112",
            "Địa chi An Toàn 113",
            "Địa chi An Toàn 114",
            "Địa chi An Toàn 115",
            "Địa chi An Toàn 116",
            "Địa chi An Toàn 117",
            "Địa chi An Toàn 118",
            "Địa chi An Toàn 119",
            "Địa chi An Toàn 120"
    };

}
